### PR TITLE
Use nodejs path list

### LINKED ISSUE #17: `pluto_to_pdf` doesn't work: `node` command not found.
The `pluto_to_pdf` function fails with the following error (taken from the log file):

```
229 error code 1
230 error path C:\Users\nicho\.julia\scratchspaces\6eb38059-8c05-41f7-8871-5e7e2697ace6\build_dir3\node_modules\puppeteer
231 error command failed
232 error command C:\Windows\system32\cmd.exe /d /s /c node install.mjs
233 error "node" non   riconosciuto come comando interno o esterno,
233 error  un programma eseguibile o un file batch.
234 verbose exit 1
```

Line 233 translates to "node is not recognized as a command or batch file". This leads me to believe that node needs to be installed on the system (which is not, in my case), but the README doesn't say nothing about it.

I'm running PlutoPDF version v1.0.3. Output of `versioninfo()`:
```
Julia Version 1.10.4
Commit 48d4fd4843 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × AMD Ryzen 7 PRO 5875U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
```

### PR DESCRIPTION
**Pull request by fonsp**
Attempt to fix #17 with help from https://github.com/JuliaPackaging/Yggdrasil/issues/9233#issuecomment-2280338850 💛

### CODE REVIEW

File: src/setup_build.jl [hunk 1]
```diff
@@ -14,6 +14,14 @@ const npm = !Sys.iswindows() ? NodeJS_20_jll.npm : let
     isfile(new) ? new : NodeJS_20_jll.npm
 end
 
+const npm_cmd = let
+    # Add NodeJS PATH to the existing PATH environment variable 
+    path_sep = Sys.iswindows() ? ';' : ':'
+    path_list = prepend!(split(get(ENV, "PATH", ""), path_sep), NodeJS_20_jll.PATH_list)
```
Comment (giordano) [inline src/setup_build.jl:20]: I would advice against doing this as a compile-time constant, because the `PATH` environment variable could change.  This likely doesn't matter much in most cases, but if users have `PATH` set differently between compile-time and run-time, then this may be relevant.

Comment (fonsp) [reply src/setup_build.jl:20]: True, thanks!

**Comment by Technici4n** [comment]
This PR does indeed seem to fix #17 :)

**Comment by fonsp** [comment]
@Technici4n The PR got stuck because the MacOS tests are failing. Maybe you could take a look and try a fix?

**Comment by fonsp** [comment]
Ubuntu test failures also happen on main, might be #22

**Comment by Technici4n** [comment]
Wow you already got to it. Thanks a lot!
